const List<String> loremIpsum = [
  'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
  'Aliquam tincidunt mauris eu risus.',
  'Vestibulum auctor dapibus neque.',
  'Nunc dignissim risus id metus.',
  'Cras ornare tristique elit.',
  'Vivamus vestibulum ntulla nec ante.',
  'Praesent placerat risus quis eros.',
  'Fusce pellentesque suscipit nibh.',
  'Integer vitae libero ac risus egestas placerat.',
  'Vestibulum commodo felis quis tortor.',
  'Ut aliquam sollicitudin leo.',
  'Cras iaculis ultricies nulla.',
  'Donec quis dui at dolor tempor interdum.',
  'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
  'Aliquam tincidunt mauris eu risus.',
  'Vestibulum auctor dapibus neque.',
  'Nunc dignissim risus id metus.',
  'Cras ornare tristique elit.',
  'Vivamus vestibulum ntulla nec ante.',
  'Praesent placerat risus quis eros.',
  'Fusce pellentesque suscipit nibh.',
  'Integer vitae libero ac risus egestas placerat.',
  'Vestibulum commodo felis quis tortor.',
  'Ut aliquam sollicitudin leo.',
  'Cras iaculis ultricies nulla.',
  'Donec quis dui at dolor tempor interdum.',
];
